### ISSUE TITLE
Won't sell legion artifact relics no matter the ilvl

### ISSUE THREAD

**Issue by jsaue003** [moody/Dejunk#106]
The addon appears to not identify or sell legion artifact relics regardless of ilvl, which doesn't make sense since they're completely useless... They can't even be used if you want to. Can we please have an update to include them? It's frustrating having to "include" them in the sell lists on every character on all 50 chars on our accounts.

**Comment by alphabitnz** [comment]
Hi @moody please add this as an option!
Would be great if "unsuitable equipment" included ALL relics unless you would rather have a discrete option for it.

Thanks so much - I didn't want to raise a duplicate for this feature request.
