### ISSUE TITLE
Deleted everything in inventory

### ISSUE THREAD

**Issue by Anfractuous17** [moody/Dejunk#110]
Today I was using Dejunk and normally Dejunk only deletes a list of selected items but for some reason it deleted every single item that was in my bags without discrimination The only items that weren't deleted were the ones equipped on my character. Please fix this

**Comment by moody** [comment]
As this is not the first such report, I am going to make some radical changes to how items are filtered as destroyable junk in the next release. In the next update, the only method Dejunk will use to check for destroyable items is by referencing the global/profile Inclusions list. This means that only items the user has manually set to destroy will be destroyed. The item's ID will be the sole factor, and no other characteristics about the item will be considered (such as quality, item level, etc.).
