### ISSUE TITLE
No consideration for Poor item quality for destroy functionality

### ISSUE THREAD

**Issue by KevinTyrrell** [moody/Dejunk#112]
If your bags are filling up and you want to collect more valuable items while destroying less valuable items, you'd ideally want to have the destroy feature be filled with white items which are on your Destroy Inclusions page **intermixed** with poor items (which are only used for vendoring). Currently Dejunk does not consider any poor items as candidates to be destroyed.

This can lead to scenarios where you begin destroying items on your Destroy Inclusions (e.g. semi-uesless white items such as conjured food, uncooked fish/meat, low selling cloth, etc) instead of destroying Poor Quality items in your bags which vendor for mere copper.

Solution: have dejunk scan Poor Quality items when pulling up the destroy window.

**Comment by KevinTyrrell** [comment]
Added feature in newly created pull request. Feature was tested on TBC-Classic and is working.

https://github.com/moody/Dejunk/compare/master...KevinTyrrell:patch-1

**Comment by moody** [comment]
Fixed in #118
