### ISSUE TITLE
Destroy all items dosent work on 9.1.5

### ISSUE THREAD

**Issue by GaneaFunpay** [moody/Dejunk#114]
Destroy all items dosent work on 9.1.5
![image](https://user-images.githubusercontent.com/61558980/140294046-a5837623-d346-487b-b90f-37f2eea24ae8.png)

**Comment by moody** [comment]
Fixed in #118 

Destroying all items at once is no longer possible as the `DeleteCursorItem()` function has been protected by Blizzard. It can now only be called once in response to a hardware event.
