### ISSUE TITLE
Got this while using Destroy frame

### ISSUE THREAD

**Issue by Jaladhjin** [moody/Dejunk#115]
1x [ADDON_ACTION_BLOCKED] AddOn 'Dejunk' tried to call the protected function 'DeleteCursorItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "@Dejunk\src\services\destroyer.lua"]:98: in function <Dejunk\src\services\destroyer.lua:86>
[string "@Dejunk\src\services\destroyer.lua"]:128: in function <Dejunk\src\services\destroyer.lua:107>
[string "@Dejunk\src\services\destroyer.lua"]:218: in function `Start'
[string "@Dejunk\src\ui\item-frames.lua"]:113: in function <Dejunk\src\ui\item-frames.lua:109>
[string "=[C]"]: ?
[string "@TomTom\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <TomTom\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@TomTom\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@TomTom\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...mTom\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by moody** [comment]
fixed in #118
