### ISSUE TITLE
Bring back the option to sell unsuitable and/or within ilvl range items

### ISSUE THREAD

**Issue by alphabitnz** [moody/Dejunk#121]
Please bring back the option to sell unsuitable and/or within ilvl range items.

That was a huge benefit of this addon, being able to do transmog runs and quickly vendor any useless BoPs

**Comment by Kyphala** [comment]
oh YES....  that function is the reason why I switch back to the old version

**Comment by moody** [comment]
Re-added the unsuitable option in #127, also added an option to include "below average equipment". Not entirely happy with it though, so I may replace it with an item level range option in the future.
