### ISSUE TITLE
Keybinds are gone.  

### ISSUE THREAD

**Issue by EyeSage** [moody/Dejunk#125]
The keybind was such a great timesaver.   

I don't understand all these changes did someone new take over.  

Drag and dropping items was so slow, keybind was amazing.

**Comment by EyeSage** [comment]
I went back to scrap - added some keybinds that I never had before on it. 

Enjoy your addon it does exactly what you like.

**Comment by moody** [comment]
Just to clarify, key bindings never actually went away. I just didn't add a command or UI button to navigate to WoW's key binding frame until #127
