### ISSUE TITLE
cloaks count as "unsuitable equipment"

### ISSUE THREAD

**Issue by potat0nerd** [moody/Dejunk#143]
backs are treated as unsuitable equipment, at least for plate characters

**Comment by alphabitnz** [comment]
+1 also experienced this on Shaman, even with a current heroic raid tier ilvl cloak

**Comment by alphabitnz** [comment]
also, the "below average ilvl" option decided to vendor a bunch of my Season 4 PVP gear, thank god for safe mode

**Comment by moody** [comment]
> also, the "below average ilvl" option decided to vendor a bunch of my Season 4 PVP gear, thank god for safe mode

Yeah the option is pretty bad. Seemed like a clever idea at the time, by the dynamic aspect of it causes issues. I want to change it to a slider for min/max ilvl range at some point.
