### ISSUE TITLE
protected functions (stopcast)

### ISSUE THREAD

**Issue by vandiel01** [moody/Dejunk#146]
`1x [ADDON_ACTION_FORBIDDEN] AddOn 'Dejunk' tried to call the protected function 'SpellStopCasting()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:519: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:519>
[string "=[C]"]: in function `SpellStopCasting'
[string "@Interface/FrameXML/UIParent.lua"]:4006: in function `ToggleGameMenu'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:292: in function `TransitionBackOpeningPanel'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:281: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:257: in function `Close'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:44: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:43>`

**Comment by vandiel01** [comment]
all i did was mouse wheel up/down to zoom in/out and get this error

**Comment by moody** [comment]
`SpellStopCasting()` is never called by Dejunk at any point, so I'm not sure if this is actually an issue with Dejunk. I will attempt to replicate it.

**Comment by Gholrua** [comment]
I'm getting something similar when trying to right click on items in my bags:

5x [ADDON_ACTION_FORBIDDEN] AddOn 'Dejunk' tried to call the protected function 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>

**Comment by artazika** [comment]
same here ^

3x [ADDON_ACTION_FORBIDDEN] Модификация 'Dejunk' пыталась вызвать защищенную функцию 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>

trying to do ecnhantment wq and can't click on item with disenchant

**Comment by moody** [comment]
Appears that these issues only occur with BugGrabber installed, at least for me.
