### ISSUE TITLE
"Dejunk has been blocked from an action only available to the Blizzard UI" 

### ISSUE THREAD

**Issue by Lucy1342** [moody/Dejunk#153]
Recently, as of October 30th on version Dejunk-1.3.2, when using Admiral's Compass, Garrison Hearthstone or Hearthstone (I presume any item that teleport to another location) error start appearing that "Dejunk has been blocked from an action only available to the Blizzard UI" with proposition to disable addon and reload UI or ignore it. If ignored error will pop up again.

![Screenshot 2022-10-30 172651](https://user-images.githubusercontent.com/11773419/198889888-49347f7a-8c15-4a87-a6a0-6c158aefc3c3.jpg)

My settings 
![Screenshot 2022-10-30 173515](https://user-images.githubusercontent.com/11773419/198890224-68ed0827-d4cc-467d-90b1-38412851970e.jpg)

**Comment by Lucy1342** [comment]
Issue not appearing on version Dejunk-1.3.1

**Comment by artazika** [comment]
not only teleport
i can't use everything from the bag like potion or click on item to desenchant it

**Comment by moody** [comment]
Yep, I broke something somehow apparently. Looking into it.

**Comment by moody** [comment]
Looks like it's because I used [`hooksecurefunc`](https://github.com/moody/Dejunk/blob/develop/src/ui/junk-frame.lua#L44) to hook the bag open/close/toggle functions. Gotta figure out an alternative for Dragonflight, but it's fine in Classic.
