### ISSUE TITLE
Adibags compatibility with Auto Junk Frame option

### ISSUE THREAD

**Issue by Vettic** [moody/Dejunk#158]
Hi 
I see my last issue (#144 ) was closed and I've just updated to 1.4.0 but I'm having an issue with the 1st function that was requested, (auto open the junk frame when the bags open).
It seems my bag addon, Adibags is interfering with this, and the junk frame wont open when my bags open. 
Any chance you could test this functionality and get the addons to work together if possible?

**Comment by moody** [comment]
Oof 😞 . Yeah, this is a little bit tricky, but I'm working on it. Whatever solution I come up with might be a bit brittle, but we'll see.

**Comment by moody** [comment]
This should be fixed in #160 (Dejunk version 1.4.1), but the code is subject to breaking if AdiBags, ArkInventory, Bagnon, or ElvUI change the name of their bag frames.
