### ISSUE TITLE
Dejunk has been blocked

### ISSUE THREAD

**Issue by DVonk** [moody/Dejunk#162]
So since 10.0 I've constantly been getting various 'addon has been blocked' messages and Dejunk is unfortunately one of them. Sometimes it seems to happen for no reason, but the one error I've been able to reproduce is when closing the options menu.

Basically every single time I go to esc -> options, and then close that menu, I get a 'Dejunk has been blocked' message. This happens always, without fail.

**Comment by tflo** [comment]
See https://github.com/moody/Dejunk/issues/166. (You can fix this yourself until the author is back. Takes 10 seconds.)
