### ISSUE TITLE
Auto open Junk Frame only on Merchant

### ISSUE THREAD

**Issue by fgmenth** [moody/Dejunk#168]
Is there a way to have the Junk Frame automatically open only on merchant and not when opening our bags? Maybe have an option for each, so people can select both if they want.

**Comment by zalidthebur** [comment]
Totally agree and why I can't use auto open as it will destroy items on the sell list when not at the merchant.
Also this was brought up here: https://github.com/moody/Dejunk/issues/152

**Comment by zalidthebur** [comment]
Thanks for the update to this :-)
