### ISSUE TITLE
When changing any keybind in combat

### ISSUE THREAD

**Issue by StellarHarbour** [moody/Dejunk#169]
1x [ADDON_ACTION_BLOCKED] AddOn 'Dejunk' tried to call the protected function 'SetBinding()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetBinding'
[string "@Interface\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua"]:357: in function <...ace\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua:353>
[string "@Interface\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua"]:394: in function <...ace\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua:380>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua"]:502: in function <...ace\AddOns\Blizzard_BindingUI\Blizzard_BindingUI.lua:499>
[string "=[C]"]: ?

**Comment by moody** [comment]
Not sure if this is something I can fix. Closing for now.
