### ISSUE TITLE
Changes required for upcoming Uncommon/Common items being added to Wardrobe

### ISSUE THREAD

**Issue by alphabitnz** [moody/Dejunk#170]
In the very near future (within 1-2 months) Blizzard are adding Common and Uncommon items to Wardrobe - they will be transmoggable.

Given this, it is immediately valuable for Dejunk to be configurable to vendor only poor items that are not Armor/Weapons, rather than all Poor items which is effectively discarding transmog items along with typical other Poor junk.

Refer this post for more information:
https://worldofwarcraft.com/en-us/news/23897170/dragonflight-in-2023-the-road-ahead

**Comment by moody** [comment]
New option added in 1.5.0 is intended to solve this: `Exclude Unbound Equipment`
