### ISSUE TITLE
grey/white transmog selling options

### ISSUE THREAD

**Issue by artazika** [moody/Dejunk#171]
can u make choose whether uncollected grey gear should be excluded from selling for our character or maybe our alts or both?

**Comment by filliph** [comment]
@moody This issue is not fixed in v1.5.0, at least not fully. It only excludes unbound gear if your character can currently equip that particular item.

F.ex. on my Druid it will sell Cloth, Mail and Plate grey items, whereas on my Paladin it will not sell the Plate item.
