### ISSUE TITLE
Please add useless items/artifact relics from Legion?

### ISSUE THREAD

**Issue by jsauerland** [moody/Dejunk#182]
90% of the stuff I have clogging up my bags isn't junk (Leatrix, or LTP, typically already cleans out junk). This stuff is great for unsuitable gear or under certain ilvl... but I have like 90 of the trash artifact relics from legion all the time. Can we have a feature to deal with these? :D

**Comment by jsaue003** [comment]
bump... Please ?

**Comment by moody** [comment]
This option was added back in version 1.5.0, which handles the Legion artifact relic item type:
![image](https://github.com/moody/Dejunk/assets/25038653/f60a0ace-079d-426b-a537-02e32075c575)

If it isn't good enough, re-open the issue with more detail please.
