### ISSUE TITLE
How do you export your 'inclusions'? 

### ISSUE THREAD

**Issue by jsauerland** [moody/Dejunk#184]
Real PITA of junking trash items is legion artifacts and crap items like food and meat from TBC. Flank of boar meat etc. How do 'backup' my inclusions in case I need to reinstall?

**Comment by moody** [comment]
![image](https://github.com/moody/Dejunk/assets/25038653/9e0b9cb1-aa29-4d1a-a30b-94c83c5dfe10)
![image](https://github.com/moody/Dejunk/assets/25038653/d078e09a-e227-40ce-b68a-b62bc514a47a)
