### ISSUE TITLE
[Request] Comma separator support for importing IDs

### ISSUE THREAD

**Issue by zeenk** [moody/Dejunk#197]
Would it be possible to also include comma as a valid separator when importing ids?
I was copying all the fated fortune card ids from Wowhead and their export system is using commas so I could not import the string they gave me so had to go into Notepad++ and do a "replace all , with ;" which was fine for me but would be nice for others that don't know how to do that so they don't have to change the separators 1 by 1 if they also want to import ids from Wowhead😄  

![2024-02-17_00-57-35](https://github.com/moody/Dejunk/assets/68170439/1c7f55a7-8125-4c93-9dd2-9fa53aa8963c)
https://www.wowhead.com/items/name:fated+fortune+card/quality:1

**Comment by zeenk** [comment]
Oh wow that was quick, I tried the changes you made and can confirm it works, thanks! :)

**Comment by moody** [comment]
It was a good idea and a very easy change to make, so thank you for that!
