### ISSUE TITLE
[Request] Search button for the Inclusion & Exclusion lists

### ISSUE THREAD

**Issue by zeenk** [moody/Dejunk#198]
Now that we have Wowhead support from #197 I thought of another idea, lets say you run Naxx 25man normal every week on multiple alts to farm something you could use this filter https://www.wowhead.com/items?filter=148;3456;0 to import ALL items that drops from that raid & mode but since it's over 500 items and maybe there is some items that you want to keep it would be nice to have a search button added so we could quickly find those items and remove them from the list 😄  

You could do something like this, *I did a paint edit at the bottom of this post to show what it could look like in Dejunk with these suggestions added*

Search bar that expands when you click on the search icon (from [Bagnon](https://www.curseforge.com/wow/addons/bagnon))

https://github.com/moody/Dejunk/assets/68170439/a3a3d8d0-f91e-459c-a302-723908229d63

Update the list live as you start typing (from [Stash](https://www.curseforge.com/wow/addons/stash))

https://github.com/moody/Dejunk/assets/68170439/74d5ce0b-7f77-4a21-b88c-9127231ae9bc

Example what  it could look like in Dejunk: (could also move the 3 buttons a bit closer to each other so they don't take up as much space ^^)
![2024-02-17_18-41-18](https://github.com/moody/Dejunk/assets/68170439/6204da07-bda0-4fef-b6f0-9805fed0f98f)
*Or you can of course do it whichever way you think is best.*

Alternative design that puts a search bar at the top of the list instead of blocking text in title when you click the search button
![Edit](https://github.com/moody/Dejunk/assets/68170439/bdca6169-d9dd-4a88-ab02-7439afd37e95)

**Comment by moody** [comment]
This is a good idea; however, I don't imagine implementing something like this until I get around to refactoring the brittle UI code I've slapped together. It'll probably be a while.

**Comment by zeenk** [comment]
Sure no problem 👍

**Comment by zeenk** [comment]
I saw that you reworked the UI a bit, nice 👍 
If you still plan to add this search feature I tried to do a new design with the new UI, maybe something you like? (just some suggestions ^^)

1. Have a toggle search icon top right next to keybinds button so you can show/hide the search bar (or you could just have it show all the time and no toggle button to hide it if you think it's good enough)
2. Move the version display to top left so it's not overlapping with search bar.
3. If it's possible you could make the search bar search in all the lists at the same time, otherwise maybe have a search icon in each list to "select this list for searching"

![2024-05-03_20-48-08](https://github.com/moody/Dejunk/assets/68170439/bce61f68-08dc-4478-a2eb-f981e67781b2)

**Comment by moody** [comment]
I had gotten a start on this idea:

![image](https://github.com/moody/Dejunk/assets/25038653/9e817655-d48c-46f1-b0c6-2716c9383e88)

But it might be better being able to search all lists at once, as you suggested. I'll play around with it and see what feels best.

**Comment by zeenk** [comment]
Awesome, thank you :)

**Comment by moody** [comment]
Thanks for the suggestions!
