### ISSUE TITLE
Help with auto destroy please.

### ISSUE THREAD

**Issue by froffy** [moody/Dejunk#199]
Hi,
Ive set up Dejunk to destroy all poor quality items
I made a macro (/dejunk destroy)
I keep getting the chat message " No junk items to destroy even though i have heaps of grey items in my bag.
It does destroy some e.g even with the window pop up at vendor it only had 14 out of 45 listed to destroy

Any help ty

**Comment by moody** [comment]
This can happen if the grey items are marked `Binds when equipped` and the `Exclude Unbound Equipment` option is enabled.
