### ISSUE TITLE
[Bug] Can't destroy 1 specific item with Dejunk

### ISSUE THREAD

**Issue by zeenk** [moody/Dejunk#200]
Tried to add this item to Dejunk but it wouldn't let me add it for some reason https://www.wowhead.com/item=169687/fragment-of-zemlans-lost-treasure-map

I can destroy it if I do it myself though, but not through Dejunk.

![2024-03-25_02-40-35](https://github.com/moody/Dejunk/assets/68170439/b6306a8a-f64d-4e91-8eca-6ec1c678398f)
![2024-03-25_02-40-44](https://github.com/moody/Dejunk/assets/68170439/99b96f7b-5811-4c70-b35d-1808c620e92a)

I see these items that has the same border can't actually be manually destroyed so that's maybe why it was blocked in Dejunk

![2024-03-25_03-34-00](https://github.com/moody/Dejunk/assets/68170439/5d3a7f17-e0ca-4df9-b296-08b0681a294e)
![2024-03-25_03-34-10](https://github.com/moody/Dejunk/assets/68170439/fa878045-4982-4ef3-ac3d-bd1db3c95796)

**Comment by moody** [comment]
Yep. Dejunk only allows for specific item qualities to be added, and all others are denied (i.e., Legendary, Artifact, and WoWToken). As far as I know, there isn't a way to check if an item can actually be destroyed or not, so I just based it on item quality.

https://github.com/moody/Dejunk/blob/0082ae9bcf1c8725e50479e96af9db0827c745e7/src/items.lua#L187-L208

**Comment by zeenk** [comment]
I see, well can close this issue now. I don't have the items anymore anyway and don't think many people will run into this scenario again :P
