### ISSUE TITLE
Version 11.0.0: DeJunk preferences frame cannot be opened

### ISSUE THREAD

**Issue by raptormama** [moody/Dejunk#217]
Since the 11.0.0 patch of Tuesday July 24, the preferences for DeJunk cannot be opened (via `/dejunk options`).

The following error is captured immediately by BugSack (I'm escaping out single quotes so that the markdown for code displays only where it should, but that's my only edit):

> 1x Blizzard_FrameXML/RestrictedFrames.lua:791: bad lizard
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:674: in function <Blizzard_FrameXML/RestrictedFrames.lua:673>
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:812: in function \`CallMethod'
[string "-- ORL_PostClick"]:9: in function <[string "-- ORL_PostClick"]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:483: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:446>
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:713: in function \`RunFor'
[string "owner:RunFor(self, ORL_PostClick, message)"]:1: in function <[string "owner:RunFor(self, ORL_PostClick, message)"]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:483: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:446>
[string "=(tail call)"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:299: in function <Blizzard_FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Now, I _am_ a dracthyr, but I don't think I'm a bad lizard. ;)

This is the only thing that happens. No chat or error message appears. This error was captured during a session in which I have never been in combat.

I really like DeJunk, so I'm hoping it's not too difficult a fix.

**Comment by moody** [comment]
There are no bad lizards, only bad Blizzards.

I can't seem to replicate the error, so I'm going to assume they broke something temporarily with the new patch.

**Comment by moody** [comment]
Reopen if you experience the issue again.

**Comment by raptormama** [comment]
Will do. It seems to have been an interaction with another addon. DeJunk works fine for me now with the latest update!
