### ISSUE TITLE
Performance issues with large lists

### ISSUE THREAD

**Issue by GreyFoxGer** [moody/Dejunk#222]
I have ported my huge list from scrap addon,

It's approximately 15 thousand records there. Now when i log into game, massive lag happing till everything is loaded, very often game just freezed. Only restart helps.

Any workaround possible?

[Dejunk.lua](https://github.com/user-attachments/files/16419541/Dejunk.zip)

**Comment by moody** [comment]
Dejunk isn't currently optimized to handle huge lists like that, but I will try finding ways to improve the performance.

**Comment by moody** [comment]
I've got changes coming that should resolve this in the next update. It'll take about 2-3 minutes to fully load all 15,000+ items on the list you shared @GreyFoxGer, but the lists are still fully functional for selling/destroying even while the item data is loading.

Scrolling and searching the lists will be impacted until all the item data is ready, of course. So, I'm adding a loading icon to provide some feedback on the status:

![image](https://github.com/user-attachments/assets/a3765426-0d2a-4a5a-a076-a55dd3a33f2a)
