### ISSUE TITLE
[Feature Request] Destroy items with left click on button when nothing left to sell

### ISSUE THREAD

**Issue by zeenk** [moody/Dejunk#230]
A small QoL feature I came up with that I think could be nice for the addon, just so you don't have to open the junk frame just to click destroy next item. 🙂 
* When there is items to sell keep the (x) number color white, but when there's only items left to destroy in your junk list then change the number to red.
* Add /Destroying to the left click function description
* Add what item that is about to be destroyed next at the bottom of the tooltip and gets updated after each item destroyed
* And when the list is empty again remove the destroy next part from the tooltip and change the (x) back to 0 and white color

![2024-09-30_18-58-18](https://github.com/user-attachments/assets/1f84c9a4-7a31-4ee7-b58e-899037d61865)
![2024-09-30_18-39-01](https://github.com/user-attachments/assets/1e9ed875-140f-422e-8eb6-464a79948d72)

**Comment by moody** [comment]
I like the idea. I'd probably implement it as an `Alt + Right-Click` action though. Similar to what I'm considering for the minimap icon: https://github.com/moody/Dejunk/issues/229#issuecomment-2384092718

**Comment by zeenk** [comment]
That's fine ^^
