### ISSUE TITLE
Minimap button tooltips bugs out with HidingBar

### ISSUE THREAD

**Issue by zeenk** [moody/Dejunk#232]
Not sure if this is a problem with [HidingBar](https://www.curseforge.com/wow/addons/hidingbar) or with Dejunk but thought I could mention it here atleast, and all other addons I have seem to be able to display their tooltips just fine in HidingBar

Works with all other addons disabled
![2024-10-03_03-16-40](https://github.com/user-attachments/assets/7c4d0f7e-462e-43b4-ab63-7bb08160ec45)

Dejunk in HidingBar 

https://github.com/user-attachments/assets/4527add0-c482-44b8-9212-229e175a3ca8

**Comment by moody** [comment]
Well, ain't that a kick in the head.

I'll look into it and try to fix it.

**Comment by zeenk** [comment]
Thanks, can confirm the fix works ^^
