### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hubbotu** [moody/Dejunk#42]
Message: Interface\AddOns\Dejunk\Modules\Dejunker.lua:121: assertion failed!
Time: Sat Apr 27 13:21:00 2019
Count: 2
Stack: Interface\AddOns\Dejunk\Modules\Dejunker.lua:121: assertion failed!
[C]: ?
Interface\AddOns\Dejunk\Modules\Dejunker.lua:121: in function `StopDejunking'
Interface\AddOns\Dejunk\Modules\Dejunker.lua:64: in function `OnEvent'
Interface\AddOns\Dejunk\Core.lua:69: in function `OnEvent'
...e\AddOns\Dejunk\Libs\DethsAddonLib\DethsAddonLib.lua:31: in function <...e\AddOns\Dejunk\Libs\DethsAddonLib\DethsAddonLib.lua:28>

Locals: (*temporary) = false

**Comment by moody** [comment]
I finally realized what is going wrong here. Might take me some time to fix it properly. In the mean time, Dejunk is going to throw an error whenever it tries to sell items to a vendor that doesn't buy items. Such as the [repair guy in Acherus](https://www.wowhead.com/npc=112881/tanjin-the-ironshaper).
