### ISSUE TITLE
Auto destroy is destroying stuff without being enabled

### ISSUE THREAD

**Issue by Geraldggg** [moody/Dejunk#60]
Mod was disabled
Enabled mod
started destroying stuff
auto destroy is not turned on
fix this shit

**Comment by moody** [comment]
- What version of Dejunk were you using?
- Did you update Dejunk without restarting the game?
- Were there any Lua errors when you re-enabled Dejunk?
- Were the items that got destroyed only items that would have been destroyed if you started destroying manually?
- Did this happen on retail or Classic?
