### ISSUE TITLE
Unable to add items to destroyables

### ISSUE THREAD

**Issue by adrnde** [moody/Dejunk#72]
Latest (as of Oct 21) version.
Hitting the set keybind to add item to destroyables does nothing.
Dragging the item to the destroyables frame also fails.

**Comment by moody** [comment]
I'm unable to reproduce this in both Classic and retail.

**Comment by adrnde** [comment]
As of 9.0.3, addon is working.  However, seeing a lot of LUA errors, enough that the UI pops up a warning about excessive errors.

9.0.3
-------
Message: Interface\AddOns\Dejunk\src\lists\list_mixins.lua:17: attempt to index field '_sv' (a nil value)
Time: Thu Oct 22 07:18:53 2020
Count: 948
Stack: Interface\AddOns\Dejunk\src\lists\list_mixins.lua:17: attempt to index field '_sv' (a nil value)
[string "@Interface\AddOns\Dejunk\src\lists\list_mixins.lua"]:17: in function `Has'
[string "@Interface\AddOns\Dejunk\src\filters\destroyer\lists.lua"]:18: in function `Run'
[string "@Interface\AddOns\Dejunk\src\filters\filters.lua"]:86: in function `Run'
[string "@Interface\AddOns\Dejunk\src\filters\filters.lua"]:119: in function `GetItems'
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:103: in function `Start'
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:44: in function <Interface\AddOns\Dejunk\src\services\destroyer.lua:38>
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:61: in function <Interface\AddOns\Dejunk\src\services\destroyer.lua:54>

Locals: self = <table> {
 localeShort = "Exclusions"
 FinalizeAdd = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:40
 GetIndex = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:103
 locale = "Destroy Exclusions"
 Remove = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:67
 helpText = "Items on this list will never be destroyed."
 RemoveAll = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:91
 uiGroup = <table> {
 }
 toAdd = <table> {
 }
 getSvar = <function> defined @Interface\AddOns\Dejunk\src\lists\lists.lua:135
 ItemCanBeAdded = <function> defined @Interface\AddOns\Dejunk\src\lists\lists.lua:117
 items = <table> {
 }
 color = "4FE34FFF"
 sibling = <table> {
 }
 GetItemIDs = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:113
 Has = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:15
 Add = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:22
}
itemID = "33226"
(*temporary) = nil
(*temporary) = "33226"
(*temporary) = "attempt to index field '_sv' (a nil value)"

**Comment by moody** [comment]
It seems like there would be more errors occurring before that one. Could you try disabling all other addons and see if you still get errors? And if you do, please post the error from the first page of the error frame.

**Comment by adrnde** [comment]
Errors, with all addons disabled except for DeJunk

--- Page 1 ---

Message: Interface\AddOns\Dejunk\src\db\reformat-db.lua:43: attempt to index local 'to' (a nil value)
Time: Fri Oct 23 22:30:45 2020
Count: 1
Stack: Interface\AddOns\Dejunk\src\db\reformat-db.lua:43: attempt to index local 'to' (a nil value)
[string "@Interface\AddOns\Dejunk\src\db\reformat-db.lua"]:43: in function <Interface\AddOns\Dejunk\src\db\reformat-db.lua:40>
[string "@Interface\AddOns\Dejunk\src\db\reformat-db.lua"]:250: in function <Interface\AddOns\Dejunk\src\db\reformat-db.lua:236>
[string "@Interface\AddOns\Dejunk\src\db\reformat-db.lua"]:280: in function `profile'
[string "@Interface\AddOns\Dejunk\src\db\reformat-db.lua"]:21: in function `ReformatDB'
[string "@Interface\AddOns\Dejunk\src\db\db.lua"]:134: in function `func'
[string "@Interface\AddOns\Dejunk\src\events\event-manager.lua"]:46: in function `Fire'
[string "@Interface\AddOns\Dejunk\src\events\event-manager.lua"]:61: in function <Interface\AddOns\Dejunk\src\events\event-manager.lua:60>

Locals: from = <table> {
 Enabled = true
 Value = 4
}
to = nil
keyMap = <table> {
 Enabled = "enabled"
 Value = "value"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Enabled = "enabled"
 Value = "value"
}
(for control) = "Enabled"
fromKey = "Enabled"
toKey = "enabled"
(*temporary) = true
(*temporary) = "attempt to index local 'to' (a nil value)"

--- Page 2 ---

Message: Interface\AddOns\Dejunk\src\lists\list_mixins.lua:17: attempt to index field '_sv' (a nil value)
Time: Fri Oct 23 22:32:27 2020
Count: 96
Stack: Interface\AddOns\Dejunk\src\lists\list_mixins.lua:17: attempt to index field '_sv' (a nil value)
[string "@Interface\AddOns\Dejunk\src\lists\list_mixins.lua"]:17: in function `Has'
[string "@Interface\AddOns\Dejunk\src\filters\destroyer\lists.lua"]:18: in function `Run'
[string "@Interface\AddOns\Dejunk\src\filters\filters.lua"]:86: in function `Run'
[string "@Interface\AddOns\Dejunk\src\filters\filters.lua"]:119: in function `GetItems'
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:103: in function `Start'
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:44: in function <Interface\AddOns\Dejunk\src\services\destroyer.lua:38>
[string "@Interface\AddOns\Dejunk\src\services\destroyer.lua"]:61: in function <Interface\AddOns\Dejunk\src\services\destroyer.lua:54>

Locals: self = <table> {
 localeShort = "Exclusions"
 FinalizeAdd = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:40
 GetIndex = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:103
 locale = "Destroy Exclusions"
 Remove = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:67
 helpText = "Items on this list will never be destroyed."
 RemoveAll = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:91
 uiGroup = <table> {
 }
 toAdd = <table> {
 }
 getSvar = <function> defined @Interface\AddOns\Dejunk\src\lists\lists.lua:135
 ItemCanBeAdded = <function> defined @Interface\AddOns\Dejunk\src\lists\lists.lua:117
 items = <table> {
 }
 color = "4FE34FFF"
 sibling = <table> {
 }
 GetItemIDs = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:113
 Has = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:15
 Add = <function> defined @Interface\AddOns\Dejunk\src\lists\list_mixins.lua:22
}
itemID = "37585"
(*temporary) = nil
(*temporary) = "37585"
(*temporary) = "attempt to index field '_sv' (a nil value)"

**Comment by moody** [comment]
Thank you so much for posting this! I see the problem, and I will have it fixed soon.
