### ISSUE TITLE
Destroying is broken as of 9.0.2

### ISSUE THREAD

**Issue by moody** [moody/Dejunk#79]
Blizzard protected the function `DeleteCursorItem()`, so auto destroy is no longer possible. However, the function can still be called in response to a hardware event.

**Comment by Finegorko** [comment]
how to call hardware event ?

**Comment by moody** [comment]
I have to update the addon to provide the ability. A lot of code needs to be reworked to support the change, but it shouldn't take too long.

**Comment by Finegorko** [comment]
so, autodestroy can still work with hardware events?

**Comment by moody** [comment]
Not properly. I'll be implementing a UI with a button to destroy items one at a time instead.

**Comment by Finegorko** [comment]
well, we'll wait! your addon is really very good. I'm wondering "manual destroy" will work in combat? and will you make it possible to bind this button for destroy.

**Comment by moody** [comment]
Yes, destroying should work in combat still. And there will be a keybind allowing you to destroy items without going through the interface (again, one item at a time to avoid certain issues).

**Comment by Finegorko** [comment]
sounds cool! I will wait
