### ISSUE TITLE
Wow Classic AutoDestroy

### ISSUE THREAD

**Issue by NYPD** [moody/Dejunk#87]
Just wanted to mention that "Auto Destroy" in 9.0.5 works great in classic. 

Since I have auto-updates turned on, I ran into the new functionality today were a new destroy window automatically appears. So I checked this project and while reading the Dejunk releases, I realized that a recent retail shadowlands patch prevented this functionality from happening. I then reverted to 9.0.5 and confirmed that the auto destroy functionality still behaves as expected in WOW classic.

I'm not sure about project priority, but perhaps Dejunk can have a classic version that continues to support the auto destroy features. Some users could benefit from this, but it might be cumbersome to maintain two different code bases depending on how much was changed to support the new shadowlands patch.

**Comment by moody** [comment]
9.0.5 is perfectly fine to use with Classic for those that prefer Auto Destroy.

I made a [fair amount of changes](https://github.com/moody/Dejunk/compare/9.0.5...9.0.7#files_bucket) between 9.0.5 and 9.0.7. So, it would not be trivial to add the old destroying code back in and have it only apply to Classic.

Still, I'm looking into solutions to bring Auto Destroy functionality back to Classic, but with Shadowlands releasing today it will probably be slow.
