### ISSUE TITLE
Shortcut doesn't destroy everything at once anymore?

### ISSUE THREAD

**Issue by 0mega42** [moody/Dejunk#88]
Hello, since a recent update a button press doesn't destroy all included items at once anymore. Is this due to an API change by Blizzard or intended behaviour? This is for Classic - I don't know about retail.

**Comment by moody** [comment]
This is related to #87. The way in which all items were destroyed previously no longer works in retail, so I've made changes to how destroying works to support the breaking change Blizzard made. For Classic, you may still use Dejunk version 9.0.5 for the old destroying functionality.

**Comment by 0mega42** [comment]
Thanks for the rapid response! That's a shame but I suppose the workaround works as long as they don't change the Classic API.
