### ISSUE TITLE
Add back StartSelling() 

### ISSUE THREAD

**Issue by ninthwalker** [moody/Dejunk#89]
For some reason the DejunkBindings_StartSelling() option was removed in 9.0.5.
I've reverted back to that version as that option was definetly nice to have for use in macros and weak auras.

If you could add it back to the latest version, that would be great as well.
This was for Retail - Shadowlands I was using it on.
Thanks!

**Comment by moody** [comment]
Adding this back for the next update. It was a mistake to remove it.

The global function `DejunkBindings_StartSelling()` will exist again, and you'll also be able to use a command:
```text
/dejunk sell start
```

**Comment by ninthwalker** [comment]
Awesome, thanks for your work on this!
