### ISSUE TITLE
Delete under gold value automatically doesn't work unless in inclusion.

### ISSUE THREAD

**Issue by bennie010697** [moody/Dejunk#99]

**Comment by moody** [comment]
Have you enabled at least one of the `Destroy > By Quality` options?

**Comment by bennie010697** [comment]
I believe how the Destroy > By Quality options work right now is: It destroys everything off that quallity.

Shouldn't there be a simple function that checks the price off an item (stack / nonstack) and give you the option to delete every item under certain value?

**Comment by moody** [comment]
You can enable the `By Quality` options alongside the `Below Price` option for this effect. This way, items that are worth more than the set price will not be sold/destroyed, even if its quality option is checked under `By Quality`.

If you add items to an `Inclusions` list, then those items will be sold/destroyed regardless of the `Below Price` option.
